# -*- coding: utf-8 -*-
"""Copy of Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IZVW3NTds5DIE5VkqNzfwYjoTaflaZMV
"""

import numpy as np
import pandas as pd

"""Data Collection & Processing"""

air_quality_data =pd.read_csv('/content/AirQualityUCI.csv', sep=';', decimal=',')

air_quality_data.head()

#removing last 2 column
air_quality_data=air_quality_data.iloc[:, :-2]

air_quality_data.head()

air_quality_data.tail()

air_quality_data.shape

air_quality_data.loc[9356]

#last data point = 9356
air_quality_data= air_quality_data.head(9357)

air_quality_data.tail()

air_quality_data.shape

air_quality_data.info()

air_quality_data.isnull().sum()

air_quality_data.isin([-200]).sum(axis=0)

"""**Handling the missing values**



"""

#-200 is null value
#replacing -200 with NaN
air_quality_data = air_quality_data.replace(to_replace= -200, value=np.NaN)

air_quality_data.isnull().sum()

air_quality_data.tail()

air_quality_data.mean(numeric_only=True)

"""Replacing the null values with mean of respective column

"""

air_quality_data = air_quality_data.fillna(air_quality_data.mean(numeric_only=True))

air_quality_data.tail()

air_quality_data.isnull().sum()

"""Two tasks cn be performed on this data

1.   **Forecasting**
2.   **Regression**

**Forecasting with *FB Prophet* Algorithm**
"""

#converting date and time to datestamp(YYYY-MM-DD HH:MM:SS)
date_info = pd.to_datetime(air_quality_data['Date'], format='%d/%m/%Y')
print(date_info)

time_info = air_quality_data['Time']
print(time_info)

time_info = time_info.apply(lambda x:x. replace('.',':'))

print(time_info)

print(type(date_info))
print(type(time_info))

#combining 2 series to a panda dataframe
date_time = pd.concat([date_info,time_info],axis=1)

date_time.head()

date_time.shape

#combining date and time column to single column
date_time['ds'] = date_time['Date'].astype(str)+' '+date_time['Time'].astype(str)

date_time.head()

date_time.info()

data = pd.DataFrame()

data['ds'] = pd.to_datetime(date_time['ds'])

data.head()

data['y']= air_quality_data['RH']

data.head()

pip install prophet

from prophet import Prophet

#training the Prophet Model

model = Prophet()
model.fit(data)

future = model.make_future_dataframe(periods=365, freq='H')
future.tail()

forecast = model.predict(future)
forecast[['ds','yhat','yhat_lower','yhat_upper']].tail()

fig1= model.plot(forecast)

fig2 = model.plot_components(forecast)

